cargo-features = ["edition"]

[package]
name = "parsec_exe_unpacker"
version = "1.0.0"
edition = "2018"
description = "Unpacker for an obscure MS-DOS executable packer using x86 emulation"
authors = ["Malte Thiesen <malte@kamalook.de>"]

[dependencies]
byteorder = "1.0"
clap = "2.29"
failure = "0.1.2"
failure-tools = "4.0.2"
unicorn = "0.8"

[dev-dependencies]
assert_matches = "1.3"
