[package]
name = "parsec_exe_unpacker"
version = "1.0.1"
edition = "2018"
description = "Unpacker for an obscure MS-DOS executable packer using x86 emulation"
authors = ["Malte Thiesen <malte@kamalook.de>"]

[dependencies]
byteorder = "1.3.2"
clap = "2.33.0"
common_failures = "0.1.1"
failure = "0.1.6"
unicorn = "0.8.0"

[dev-dependencies]
assert_matches = "1.3.0"
tempfile = "3.1.0"
sha2 = "0.8.1"
digest = { version = "0.8.1", features = ["std"] }
